### ISSUE TITLE
dowlaod wordlists

### ISSUE THREAD

**Issue by Nickpete** [Mebus/cupp#3]
Hi, I have just installed cup, and when I try to download wordlist, I get this error message.
[+] connecting...
Traceback (most recent call last):
  File "cupp.py", line 905, in <module>
    ftp = ftplib.FTP(ftpurl)
  File "/usr/lib/python2.7/ftplib.py", line 117, in __init__
    self.connect(host)
  File "/usr/lib/python2.7/ftplib.py", line 132, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

Can you help me resolve the issue?
Thank you for your help.

**Comment by Mebus** [comment]
Hey Nickpete,

that's because the FTP Server and 

ftp://ftp.ox.ac.uk/pub/wordlists/dictionaries

does not exist any more. Does anybody know an alternative mirror for this?

Mebus
