### ISSUE TITLE
Error when running test_cupp.py on windows

### ISSUE THREAD

**Issue by paun93** [Mebus/cupp#48]
I've ran the test_cupp.py with Python 3.7.3 (and 3.6.8) and it has come up with the following error:

>ERROR: test_generate_wordlist_from_profile (__main__.TestCupp)
>----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "test_cupp.py", line 66, in test_generate_wordlist_from_profile
>    generate_wordlist_from_profile(profile)
>  File "C:\Users\josipp\Downloads\cupp\cupp.py", line 691, in generate_wordlist_from_profile
>    print_to_file(profile["name"] + ".txt", unique_list_finished)
>  File "C:\Users\josipp\Downloads\cupp\cupp.py", line 122, in print_to_file
>    f.write(os.linesep.join(unique_list_finished))
>  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
>    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
>UnicodeEncodeError: 'charmap' codec can't encode characters in position 38696-38700: >character maps to  \<undefined>

When I run it on Ubuntu (Python 3.6.9 version) it is able to complete all the tests and give me the "OK" message at the end. I'm not sure if I'm doing anything wrong when running it on Windows. What should I do for all tests to work?

In both cases cupp.py works.

Thank you in advance for replying!

**Comment by g33k247** [comment]
Did you ever get this to work?
