### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by mertct11** [Mebus/cupp#51]
hi,

ı run with one parameter (-i) and answered questions... but the end seeing is this error please help me ! 

 [+] Now making a dictionary...
[+] Sorting list and removing duplicates...
Traceback (most recent call last):
  File "cupp.py", line 1078, in <module>
    main()
  File "cupp.py", line 1022, in main
    interactive()
  File "cupp.py", line 356, in interactive
    generate_wordlist_from_profile(profile)  # generate the wordlist
  File "cupp.py", line 691, in generate_wordlist_from_profile
    print_to_file(profile["name"] + ".txt", unique_list_finished)
  File "cupp.py", line 120, in print_to_file
    f = open(filename, "w")
PermissionError: [Errno 13] Permission denied: '****.txt'

thanxx!!

**Comment by ma1ware07** [comment]
Run the program with sudo.

**Comment by Mebus** [comment]
Seems you are not allowed to write in the current directory. This is not a bug.
